# -*- coding: utf-8 -*-
"""Trt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SYtblyxEA1GnYItFMea7fc4Ut_jfODE1
"""



import onnx
import onnx.helper
import onnx.numpy_helper
import numpy as np
import onnxruntime as rt

# Define input: x (3x1 vector)
input_tensor = onnx.helper.make_tensor_value_info('x', onnx.TensorProto.FLOAT, [3, 1])

# Define output: Y (4x1 vector)
output_tensor = onnx.helper.make_tensor_value_info('Y', onnx.TensorProto.FLOAT, [4, 1])

# Define constants: A (4x3 matrix) and b (4x1 vector)
A = np.random.rand(4, 3).astype(np.float32)  # Example values for A
b = np.random.rand(4, 1).astype(np.float32)  # Example values for b

# Create ONNX tensors for A and b
A_tensor = onnx.helper.make_tensor('A', onnx.TensorProto.FLOAT, A.shape, A.flatten())
b_tensor = onnx.helper.make_tensor('b', onnx.TensorProto.FLOAT, b.shape, b.flatten())

# Create the node for matrix multiplication (A * x)
matmul_node = onnx.helper.make_node(
    'MatMul',
    inputs=['A', 'x'],  # Inputs: A (constant), x (input)
    outputs=['Ax']      # Output: Ax
)

# Create the node for addition (Ax + b)
add_node = onnx.helper.make_node(
    'Add',
    inputs=['Ax', 'b'],  # Inputs: Ax, b (constant)
    outputs=['Y']        # Output: Y
)

# Create the computation graph
graph = onnx.helper.make_graph(
    nodes=[matmul_node, add_node],  # List of nodes
    name='LinearModel',            # Graph name
    inputs=[input_tensor],         # Model inputs
    outputs=[output_tensor],       # Model outputs
    initializer=[A_tensor, b_tensor]  # Initialize constants A and b
)

# Create the model
model = onnx.helper.make_model(graph, producer_name='example-onnx')

# Save the model to a file
onnx.save(model, 'linear_model.onnx')
print("ONNX model saved as 'linear_model.onnx'.")




# Load the model
session = rt.InferenceSession('linear_model.onnx')

# Prepare input
input_name = session.get_inputs()[0].name
output_name = session.get_outputs()[0].name
x_input = np.random.rand(3, 1).astype(np.float32)  # Example input

# Run inference
output = session.run([output_name], {input_name: x_input})
print("Input x:", x_input)
print("Output Y:", output[0])

